apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "mc-%s-pv" .Values.mcVersion}}
spec:
  capacity:
    storage: {{ .Values.resources.storage_size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: {{ .Values.resources.storage_path }}