apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "mc-%s-pvc" .Values.mcVersion}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.resources.storage_size | quote }}
  storageClassName: local-path